# Generated by Django 5.0.1 on 2025-11-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_servicecategory_artisanprofile_portfolioitem_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.URLField(help_text='Image URL (Cloudinary or external)', max_length=500),
        ),
    ]
